This is the code that is used to generate the SERA demand inputs and network links

 - Starting with the latest STIEVE inputs (taz demands)
 - remove the smallest TAZ demands and consolidate them to the nearest TAZ
 - use k-means clusters to futher group the TAZs into larger TAZs
 - map (using Folium) the old and new TAZ locations 
 - generate the new SERA demands input file
 - generate all candidate networks (using delaunay and gabriel algorithms)
 - write the new SERA links file 
 
 - added new plant locations (Aug 2023) so some of the code is being modified

In [2]:
#####
## Library loads
#####
import geopy.distance
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns; sns.set()
import csv
import folium
import geopandas
import geopy.distance
import copy
from scipy.spatial import Delaunay
import math

In [3]:
####
# LOAD TAZ STIEVE CSV
###
df = pd.read_csv('../TAZ_hydrogen_demand_2025_2040.csv')
# df = pd.read_excel("CA_StatDemandsHigh.xls",sheet_name="taz")
print(len(df))
# display(df)
df=pd.pivot_table(df, values = 'hydrogen_kg_allocated_per_day', index=['Name','latitude','longitude'], columns = 'year').reset_index()
#df=df.sort_values(by=[2050])
tazdem = df.rename_axis(None, axis=1)
tazdem['Notes']=""
origtazdem=tazdem.copy(deep=True)
###
df

1057

year,Name,latitude,longitude,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040
0,Bakersfield,35.060661,-118.969539,127.954676,434.403336,583.129073,617.198073,682.000557,794.078188,934.210278,1106.476267,1301.963710,1532.618172,1780.506859,2057.381512,2321.396363,2568.181640,2808.399340,3143.759979
1,Cluster_1,34.111960,-117.628111,NaN,NaN,NaN,NaN,NaN,NaN,2523.314128,2988.606808,3516.620939,4139.621646,4809.172219,5557.014262,6270.121813,6936.692061,7585.523197,8491.336653
2,Cluster_10,37.323479,-122.031270,NaN,NaN,NaN,NaN,NaN,NaN,2639.446423,3126.153602,3678.468906,4330.142421,5030.508200,5812.768714,6558.696125,7255.944414,7934.637170,8882.139528
3,Cluster_100,37.640949,-121.025245,NaN,NaN,4004.195961,4238.138940,4683.120771,5452.728768,6414.979449,7597.885274,8940.246798,10524.091111,12226.278371,14127.504733,15940.426174,17635.036605,19284.549186,21587.383637
4,Cluster_101,37.953434,-122.040738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2334.626601,2712.233713,3133.994946,3536.166931,3912.093227,4278.015178,4788.867708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,Mojave,35.002833,-118.158635,200.587524,680.990269,914.139444,967.547546,1069.134842,1244.832794,1464.510180,1734.562116,2041.017052,2402.601394,2791.202884,3225.244081,3639.125673,4025.997407,4402.573511,4928.299980
143,Oakland,37.748749,-122.191906,123.367691,418.830619,562.224758,595.072435,657.551845,765.611659,900.720221,1066.810729,1255.290236,1477.676077,1716.678321,1983.627427,2238.177736,2476.116126,2707.722376,3031.060833
144,Orland,39.740147,-122.203058,1456.123730,4943.508306,6636.006625,7023.711716,7761.163729,9036.606743,10631.309389,12591.695686,14816.342045,17441.188944,20262.161256,23412.993746,26417.481740,29225.897251,31959.573755,35775.976553
145,Santa Nella,37.110064,-121.014661,338.867289,1150.447056,1544.323144,1634.549387,1806.168295,2102.987794,2474.104995,2930.323637,3448.040549,4058.891630,4715.384770,5448.642558,6147.843238,6801.414175,7437.591945,8325.740420
146,W. Sacramento,38.575739,-121.575826,620.324113,2105.986836,2827.009025,2992.175496,3306.337855,3849.690072,4529.050270,5364.195572,6311.918455,7430.131003,8631.895051,9974.183025,11254.126695,12450.541414,13615.116524,15240.944490

In [5]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors

# Load the files
csv_data = df
tsv_data = pd.read_csv('../Cleaning TAZ Clustering/nodes_new484_newLoc_TAZ.tsv', sep='\t')

# Filter only TAZ entries
taz_data = tsv_data[tsv_data['Network ID'].str.startswith('TAZ_')].copy()

# Extract numeric TAZ number
taz_data['TAZ'] = taz_data['Network ID'].str.extract('TAZ_(\d+)').astype(int)

# Rename coordinates to match
taz_data = taz_data.rename(columns={'X': 'longitude', 'Y': 'latitude'})

# First, try exact matches
merged = pd.merge(csv_data, taz_data[['latitude', 'longitude', 'TAZ']], on=['latitude', 'longitude'], how='left')

# Find rows without exact match
missing_taz = merged[merged['TAZ'].isna()]

if not missing_taz.empty:
    # Nearest neighbor matching for missing
    neigh = NearestNeighbors(n_neighbors=1)
    neigh.fit(taz_data[['latitude', 'longitude']])

    distances, indices = neigh.kneighbors(missing_taz[['latitude', 'longitude']])

    # Assign nearest TAZ
    merged.loc[missing_taz.index, 'TAZ'] = taz_data.iloc[indices.flatten()]['TAZ'].values

# Save result
# Force TAZ to integer
merged['TAZ'] = merged['TAZ'].round().astype('Int64')

merged#.to_csv('/mnt/data/TAZ_hydrogen_demand_with_TAZ.csv', index=False)

,Name,latitude,longitude,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,TAZ
0,Bakersfield,35.060661,-118.969539,127.954676,434.403336,583.129073,617.198073,682.000557,794.078188,934.210278,1106.476267,1301.963710,1532.618172,1780.506859,2057.381512,2321.396363,2568.181640,2808.399340,3143.759979,2795
1,Cluster_1,34.111960,-117.628111,NaN,NaN,NaN,NaN,NaN,NaN,2523.314128,2988.606808,3516.620939,4139.621646,4809.172219,5557.014262,6270.121813,6936.692061,7585.523197,8491.336653,5050
2,Cluster_10,37.323479,-122.031270,NaN,NaN,NaN,NaN,NaN,NaN,2639.446423,3126.153602,3678.468906,4330.142421,5030.508200,5812.768714,6558.696125,7255.944414,7934.637170,8882.139528,1734
3,Cluster_100,37.640949,-121.025245,NaN,NaN,4004.195961,4238.138940,4683.120771,5452.728768,6414.979449,7597.885274,8940.246798,10524.091111,12226.278371,14127.504733,15940.426174,17635.036605,19284.549186,21587.383637,2247
4,Cluster_101,37.953434,-122.040738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2334.626601,2712.233713,3133.994946,3536.166931,3912.093227,4278.015178,4788.867708,1379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,Mojave,35.002833,-118.158635,200.587524,680.990269,914.139444,967.547546,1069.134842,1244.832794,1464.510180,1734.562116,2041.017052,2402.601394,2791.202884,3225.244081,3639.125673,4025.997407,4402.573511,4928.299980,3678
143,Oakland,37.748749,-122.191906,123.367691,418.830619,562.224758,595.072435,657.551845,765.611659,900.720221,1066.810729,1255.290236,1477.676077,1716.678321,1983.627427,2238.177736,2476.116126,2707.722376,3031.060833,1480
144,Orland,39.740147,-122.203058,1456.123730,4943.508306,6636.006625,7023.711716,7761.163729,9036.606743,10631.309389,12591.695686,14816.342045,17441.188944,20262.161256,23412.993746,26417.481740,29225.897251,31959.573755,35775.976553,233
145,Santa Nella,37.110064,-121.014661,338.867289,1150.447056,1544.323144,1634.549387,1806.168295,2102.987794,2474.104995,2930.323637,3448.040549,4058.891630,4715.384770,5448.642558,6147.843238,6801.414175,7437.591945,8325.740420,2305
146,W. Sacramento,38.575739,-121.575826,620.324113,2105.986836,2827.009025,2992.175496,3306.337855,3849.690072,4529.050270,5364.195572,6311.918455,7430.131003,8631.895051,9974.183025,11254.126695,12450.541414,13615.116524,15240.944490,313

In [8]:
from IPython.core.magic import register_cell_magic

@register_cell_magic
def skip(line, cell):
    return

In [10]:
%%skip #skipping this because we alrady did all the clustering

####
# MAKE DISTANCE MATRIX FOR ALL TAZS
###
df['coord']=list(zip(df['latitude'],df['longitude']))

listofcoord=list(df['coord'])
tazmatrix=df[['Name','coord']]
listoftazs=list(tazmatrix['Name'])
listofcols=['Name','coord']+listoftazs
tazmatrix=tazmatrix.reindex(columns=listofcols, fill_value=0)

print(len(listofcoord))
print(len(listoftazs))
print(len(df))

for i in range(0,len(df)):
    for j in range(i+1,len(df)):
        # print(i,j)
        tmpdist=geopy.distance.geodesic(listofcoord[i], listofcoord[j]).km
        tazmatrix[listoftazs[j]].iloc[i]=tmpdist
        tazmatrix[listoftazs[i]].iloc[j]=tmpdist
tazmatrix=tazmatrix.reset_index()

origtazmatrix=tazmatrix.copy(deep=True)
#####  tazmatrix is the df matrix of all the distances between TAZs


tazmatrix

In [11]:
%%skip #skipping this because we alrady did all the clustering

####
# consolidate TAZs with small demands
#####

threshold = 1000
# find the TAZs with small demands in 2050
smalltazlist=list(df[df[2050]<threshold]['TAZ12'])
print(len(smalltazlist),"small TAZs to add to next closest TAZ")
# ",".join([str(i) for i in smalltazlist])

In [12]:
%%skip #skipping this because we alrady did all the clustering

#####
##TAZ consolidation so small tazs below threshold size are added to nearest one
#####
tazmatrix=origtazmatrix.copy(deep=True)
tazdem=origtazdem.copy(deep=True)
tazdem=tazdem.fillna(0)
# Rows are the TO element and columns to the right are the FROM element
# if we remove all small TAZ rows we can find TAZs that are closest to the small TAZ (col)

for taz in smalltazlist:
    tazmatrix = tazmatrix[tazmatrix['TAZ12'] != taz]
print(origtazmatrix.shape,tazmatrix.shape)

yrs=[2025,2030,2035,2040,2045,2050]

# go through list of small tazs and then look at the column for the TAZ in question
# sort it from low to high and the next row (after it's own row) is the closest TAZ.
# add the small TAZ's demands to this row in the 
for smalltaz in smalltazlist:
    tazmatrix=tazmatrix.sort_values(by=[smalltaz])
    # display(tazmatrix.iloc[0:2,:])
    closesttaz=tazmatrix['TAZ12'].iloc[1]
    dist=tazmatrix[smalltaz].iloc[1]
    
    ftpair=[smalltaz,closesttaz] #from/to pair
    print(closesttaz, "is the closest to", smalltaz,"-", dist,"km away")
    
    # pair=[171,109]
    for yr in yrs:
        tazdem.loc[tazdem['TAZ12'] == ftpair[1], yr]+=float(tazdem.loc[tazdem['TAZ12'] == ftpair[0], yr])
    tazdem.loc[tazdem['TAZ12'] == ftpair[1], 'Notes']=ftpair[0]
    tazdem=tazdem[tazdem['TAZ12']!=ftpair[0]]
    print(len(tazdem))

In [13]:
%%skip #skipping this because we alrady did all the clustering


#####
# K_means elbow analysis - try different cluster number and see which number leads to small
# error while reducing number significantly
###
K_clusters = [15,25,35,50,60,75,100,125,150,200,225]
kmeans = [KMeans(n_clusters=i) for i in K_clusters]
Y_axis = tazdem[['Lat']]
X_axis = tazdem[['Lon']]
score = [kmeans[i].fit(Y_axis).score(Y_axis) for i in range(len(kmeans))]
# Visualize
plt.plot(K_clusters, score)
plt.xlabel('Number of Clusters')
plt.ylabel('Score')
plt.title('Elbow Curve')
plt.show()

In [14]:
%%skip #skipping this because we alrady did all the clustering


#####
##. This section uses the kmeans algorithm to cluster the TAZs
## specify the number of clusters to use
## output in tazdem tells you which cluster each TAZ belongs to
###
targetTAZ=484

Ncluster=targetTAZ

tazdem['Ntaz']=1
tazdem=tazdem.sort_values(2050, ascending=False)
kmeans = KMeans(n_clusters = Ncluster, init ='k-means++')
kmeans.fit(tazdem[tazdem.columns[1:3]]) # Compute k-means clustering.
tazdem['cluster_label'] = kmeans.fit_predict(tazdem[tazdem.columns[1:3]])
centers = kmeans.cluster_centers_ # Coordinates of cluster centers.
labels = kmeans.predict(tazdem[tazdem.columns[1:3]]) # Labels of each point
tazdem

In [15]:
%%skip #skipping this because we alrady did all the clustering


####
# Kmeans indicates which cluster each TAZ belongs to
# then we groupby by the cluster names which reduces the number
# and sum the demands (assigning the clusters to the largest TAZ in each cluster
###
tazdem2=tazdem.copy(deep=True)
tazdem2['Names']=tazdem2['TAZ12'].astype(str)+" "+tazdem2['Notes'].astype(str) #df["Year"].astype(str) + df["quarter"]
tazdem2=tazdem2.groupby('cluster_label', as_index=False).agg({'TAZ12':'first', 'Lat':'first', 'Lon':'first',2025:'sum',2030:'sum',2035:'sum',2040:'sum',2045:'sum',2050:'sum','Ntaz':'sum','Names':','.join})
# df2['Names']=df2['Names'].str.replace("\n"," ")
# tazdem2

In [16]:
%%skip #I do not think we need this

orighublocations=[531,1408,2312,2947,4619,6424]
hublocations= [534,1480,2312,2947,4619,6412]
hubclusters=[]
for i in range(len(hublocations)):
    cluster=tazdem[tazdem['TAZ12']==hublocations[i]].iloc[0]['cluster_label']
    hubclusters.append(cluster)
print(hubclusters)

######
# ADD HUBS Demand?
# this section looks at 6 hubs that Vishnu used and determines which of the demand clusters
# the hubs shoudl go in (since the taz clustering may have a different name than the the 
# hub TAZ
####
ADDHUBS=False
#####
if ADDHUBS==True:
    print('true')
    hubdemands = pd.read_csv('hub demands.tsv',sep='\t')
    hubdemands['TAZ']=hubdemands['Network ID'].str.replace("TAZ_","")
    display(hubdemands)
    hubtazs=list(tazdem2[tazdem2['cluster_label'].isin(hubclusters)]['TAZ12'].unique())
    hubtazs.sort()
    display(hubtazs)

In [17]:
%%skip #I do not think I need this

###########
#### Interpolate the columns to get demand for each and every year
#### melt dataframe from wide to make long
#### make dataframe fit the SERA demand inputs file format and export to tsv
######
tazdem3=tazdem2.copy(deep=True)
tazdem3=tazdem3[['TAZ12',2025,2030,2035,2040,2045,2050]]
toadd=list(range(2025,2051))
for i in toadd:
    if i not in yrs:
        tazdem3[i]=np.nan
tazdem3=tazdem3[['TAZ12']+toadd]
tazdem4=tazdem3.interpolate(axis=1)
tazdem4['TAZ12']=tazdem4['TAZ12'].astype(int)
# tazdem4=tazdem4.rename({'TAZ12':'Network ID'})
tazdem4.rename({'TAZ12':'Network ID'}, axis=1, inplace=True)
tazdem4['Network ID']="TAZ_"+tazdem4['Network ID'].astype(str)
# print(len(tazdem4))
# display(tazdem4)

tazdemlong= pd.melt(tazdem4, id_vars='Network ID', value_vars=list(range(2025,2051)))
tazdemlong = tazdemlong.rename({'value': 'Fueling-Station Demand [kg]','variable':'Year'}, axis='columns')
tazdemlong=tazdemlong[tazdemlong['Fueling-Station Demand [kg]']>0]
tazdemlong['Period']='1 Year'
othercols=['Ammonia [kg]','Biofuels [kg]','Methanol [kg]','FT Fuels [kg]','Metals [kg]','Natural Gas Blending [kg]','Seasonal Grid Storage [kg]','Other [kg]']
for coln in othercols:
    tazdemlong[coln]=0
        
#### convert fueling kg/day to kg/yr
tazdemlong['Fueling-Station Demand [kg]']=round(tazdemlong['Fueling-Station Demand [kg]']*365*100)/100
# tazdemlong['Network ID']="TAZ_"+tazdemlong['Network ID'].astype(str)

#### Add in Hub demands
if ADDHUBS==True:

    for i in range(len(hubdemands)):
        oldtaz=int(hubdemands.loc[i,'TAZ'])
        yr=int(hubdemands.loc[i,'Year'])
        clusterindex=hublocations.index(oldtaz)
        newtaz="TAZ_"+str(hubtazs[clusterindex])
        # print(yr, newtaz,hubdemands.loc[i,'Other [kg]'])
        tazdemlong.loc[(tazdemlong['Network ID']==newtaz) & (tazdemlong['Year']==yr),'Other [kg]']=hubdemands.loc[i,'Other [kg]']
    demfilename='newdemand_hubs_'+str(targetTAZ)+'TAZ.tsv'
else:
    demfilename='newdemand_newLoc_'+str(targetTAZ)+'TAZ.tsv'
tazdemlong=tazdemlong[['Network ID','Year','Period','Fueling-Station Demand [kg]','Ammonia [kg]','Biofuels [kg]','Methanol [kg]','FT Fuels [kg]','Metals [kg]','Natural Gas Blending [kg]','Seasonal Grid Storage [kg]','Other [kg]']]



tazdemlong.to_csv(demfilename, sep = '\t',index=False)
# display(hubdemands)
tazdemlong

In [26]:
df_long = pd.melt(df, id_vars='Name', value_vars=list(range(2025,2041)))
df_long = df_long.rename({'value': 'Fueling-Station Demand [kg]','year':'Year', 'Name': 'Network_ID'}, axis='columns')
df_long=df_long[df_long['Fueling-Station Demand [kg]']>0]  # removing NaN
df_long['Period']='1 Year'
othercols=['Ammonia [kg]','Biofuels [kg]','Methanol [kg]','FT Fuels [kg]','Metals [kg]','Natural Gas Blending [kg]','Seasonal Grid Storage [kg]','Other [kg]']
for coln in othercols:
    df_long[coln]=0

df_long.to_csv('truckiing_demand_147_stations', sep = '\t',index=False)
df_long

,Network_ID,Year,Fueling-Station Demand [kg],Period,Ammonia [kg],Biofuels [kg],Methanol [kg],FT Fuels [kg],Metals [kg],Natural Gas Blending [kg],Seasonal Grid Storage [kg],Other [kg]
0,Bakersfield,2025,127.954676,1 Year,0,0,0,0,0,0,0,0
138,Coachella,2025,612.025440,1 Year,0,0,0,0,0,0,0,0
139,Fowler,2025,435.927418,1 Year,0,0,0,0,0,0,0,0
140,Los Angeles,2025,192.214220,1 Year,0,0,0,0,0,0,0,0
141,Lost Hills,2025,298.054452,1 Year,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2347,Mojave,2040,4928.299980,1 Year,0,0,0,0,0,0,0,0
2348,Oakland,2040,3031.060833,1 Year,0,0,0,0,0,0,0,0
2349,Orland,2040,35775.976553,1 Year,0,0,0,0,0,0,0,0
2350,Santa Nella,2040,8325.740420,1 Year,0,0,0,0,0,0,0,0
2351,W. Sacramento,2040,15240.944490,1 Year,0,0,0,0,0,0,0,0

In [27]:
%%skip #I do not think I need this
###########
#### Interpolate the columns to get demand for each and every year
#### melt dataframe from wide to make long
#### make dataframe fit the SERA demand inputs file format and export to tsv
######
tazdem3=tazdem2.copy(deep=True)
tazdem3=tazdem3[['TAZ12',2025,2030,2035,2040,2045,2050]]
toadd=list(range(2025,2051))
for i in toadd:
    if i not in yrs:
        tazdem3[i]=np.nan
tazdem3=tazdem3[['TAZ12']+toadd]
tazdem4=tazdem3.interpolate(axis=1)
tazdem4['TAZ12']=tazdem4['TAZ12'].astype(int)
# tazdem4=tazdem4.rename({'TAZ12':'Network ID'})
tazdem4.rename({'TAZ12':'Network ID'}, axis=1, inplace=True)
tazdem4['Network ID']="TAZ_"+tazdem4['Network ID'].astype(str)
# print(len(tazdem4))
# display(tazdem4)

tazdemlong= pd.melt(tazdem4, id_vars='Network ID', value_vars=list(range(2025,2051)))
tazdemlong = tazdemlong.rename({'value': 'Fueling-Station Demand [kg]','variable':'Year'}, axis='columns')
tazdemlong=tazdemlong[tazdemlong['Fueling-Station Demand [kg]']>0]
tazdemlong['Period']='1 Year'
othercols=['Ammonia [kg]','Biofuels [kg]','Methanol [kg]','FT Fuels [kg]','Metals [kg]','Natural Gas Blending [kg]','Seasonal Grid Storage [kg]','Other [kg]']
for coln in othercols:
    tazdemlong[coln]=0
        
#### convert fueling kg/day to kg/yr
tazdemlong['Fueling-Station Demand [kg]']=round(tazdemlong['Fueling-Station Demand [kg]']*365*100)/100
# tazdemlong['Network ID']="TAZ_"+tazdemlong['Network ID'].astype(str)

#### Add in Hub demands
if ADDHUBS==True:

    for i in range(len(hubdemands)):
        oldtaz=int(hubdemands.loc[i,'TAZ'])
        yr=int(hubdemands.loc[i,'Year'])
        clusterindex=hublocations.index(oldtaz)
        newtaz="TAZ_"+str(hubtazs[clusterindex])
        # print(yr, newtaz,hubdemands.loc[i,'Other [kg]'])
        tazdemlong.loc[(tazdemlong['Network ID']==newtaz) & (tazdemlong['Year']==yr),'Other [kg]']=hubdemands.loc[i,'Other [kg]']
    demfilename='newdemand_hubs_'+str(targetTAZ)+'TAZ.tsv'
else:
    demfilename='newdemand_newLoc_'+str(targetTAZ)+'TAZ.tsv'
tazdemlong=tazdemlong[['Network ID','Year','Period','Fueling-Station Demand [kg]','Ammonia [kg]','Biofuels [kg]','Methanol [kg]','FT Fuels [kg]','Metals [kg]','Natural Gas Blending [kg]','Seasonal Grid Storage [kg]','Other [kg]']]



tazdemlong.to_csv(demfilename, sep = '\t',index=False)
# display(hubdemands)
tazdemlong

In [28]:
%%skip #I do not think I need this
#####
# Make a Folium (leaflet) map of the original taz and the new clustered TAZs
# and save the interactive map
#####

map = folium.Map(location=[origtazdem.Lat.mean(), df.Lon.mean()], 
                 # width=300,height=400,
                 tiles="cartodbpositron", zoom_start=5, control_scale=True)
map
lat=list(origtazdem.Lat)
lon=list(origtazdem.Lon)
size=list(origtazdem.loc[:,2050])
names=list(origtazdem.TAZ12)

feature_group=folium.FeatureGroup('original')
for i in range(len(origtazdem)):
   
    folium.Circle(
        radius=10*size[i]**.5,
        location=[lat[i], lon[i]],
        popup=str(names[i])+"-"+str(round(size[i])),
        color="blue",
        fill_color="blue",
        fill_opacity=1,
        fill=True,
    ).add_to(feature_group)
    
feature_group.add_to(map)


lat2=list(tazdem2.Lat)
lon2=list(tazdem2.Lon)
size2=list(tazdem2.loc[:,2050])
names2=list(tazdem2.Names)
Ntaz=list(tazdem2.Ntaz)

feature_group=folium.FeatureGroup('clustered')
for i in range(len(tazdem2)):
    if Ntaz[i]>1:
        outcolor="darkred"
    else: 
        outcolor="red"
    folium.Circle(
        radius=10*size2[i]**.5,
        location=[lat2[i], lon2[i]],
        popup=str(Ntaz[i])+" taz\n"+str(round(size2[i]))+" kg/d\ntaz#\n"+str(names2[i]),
        color=outcolor,
        fill=True,
        fill_opacity=1,
    ).add_to(feature_group)
feature_group.add_to(map)
folium.LayerControl().add_to(map)

map.save('TAZ_newLoc_'+str(targetTAZ)+'.html')
map

In [35]:
df

year,Name,latitude,longitude,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,coord
0,Bakersfield,35.060661,-118.969539,127.954676,434.403336,583.129073,617.198073,682.000557,794.078188,934.210278,1106.476267,1301.963710,1532.618172,1780.506859,2057.381512,2321.396363,2568.181640,2808.399340,3143.759979,"(35.060661, -118.969539)"
1,Cluster_1,34.111960,-117.628111,NaN,NaN,NaN,NaN,NaN,NaN,2523.314128,2988.606808,3516.620939,4139.621646,4809.172219,5557.014262,6270.121813,6936.692061,7585.523197,8491.336653,"(34.1119600611685, -117.62811097272456)"
2,Cluster_10,37.323479,-122.031270,NaN,NaN,NaN,NaN,NaN,NaN,2639.446423,3126.153602,3678.468906,4330.142421,5030.508200,5812.768714,6558.696125,7255.944414,7934.637170,8882.139528,"(37.323479176408185, -122.03126957594444)"
3,Cluster_100,37.640949,-121.025245,NaN,NaN,4004.195961,4238.138940,4683.120771,5452.728768,6414.979449,7597.885274,8940.246798,10524.091111,12226.278371,14127.504733,15940.426174,17635.036605,19284.549186,21587.383637,"(37.64094859021344, -121.0252454639227)"
4,Cluster_101,37.953434,-122.040738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2334.626601,2712.233713,3133.994946,3536.166931,3912.093227,4278.015178,4788.867708,"(37.953434316312105, -122.0407377791888)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,Mojave,35.002833,-118.158635,200.587524,680.990269,914.139444,967.547546,1069.134842,1244.832794,1464.510180,1734.562116,2041.017052,2402.601394,2791.202884,3225.244081,3639.125673,4025.997407,4402.573511,4928.299980,"(35.002833, -118.158635)"
143,Oakland,37.748749,-122.191906,123.367691,418.830619,562.224758,595.072435,657.551845,765.611659,900.720221,1066.810729,1255.290236,1477.676077,1716.678321,1983.627427,2238.177736,2476.116126,2707.722376,3031.060833,"(37.748749, -122.191906)"
144,Orland,39.740147,-122.203058,1456.123730,4943.508306,6636.006625,7023.711716,7761.163729,9036.606743,10631.309389,12591.695686,14816.342045,17441.188944,20262.161256,23412.993746,26417.481740,29225.897251,31959.573755,35775.976553,"(39.740147, -122.203058)"
145,Santa Nella,37.110064,-121.014661,338.867289,1150.447056,1544.323144,1634.549387,1806.168295,2102.987794,2474.104995,2930.323637,3448.040549,4058.891630,4715.384770,5448.642558,6147.843238,6801.414175,7437.591945,8325.740420,"(37.110064, -121.014661)"
146,W. Sacramento,38.575739,-121.575826,620.324113,2105.986836,2827.009025,2992.175496,3306.337855,3849.690072,4529.050270,5364.195572,6311.918455,7430.131003,8631.895051,9974.183025,11254.126695,12450.541414,13615.116524,15240.944490,"(38.575739, -121.575826)"

In [34]:
##### make links / geography file for SERA inputs
## open old sera geometry file and extract WECC and Cavern locations
## i will make new link and TAZ locations
#####
WECC_inCA=[ 'WECC_IID', 'WECC_SCE', 'WECC_SF',  'WEC_CALN', 'WEC_LADW', 'WEC_SDGE', 'PL_CA1','PL_CA2','PL_CA3','PL_CA4','PL_CA5','PL_CA6','PL_CA7']
WECC_outCA=['WECC_AZ', 'WECC_CO', 'WECC_ID', 'WECC_MT', 'WECC_NM', 'WECC_NNV', 'WECC_PNW', 'WECC_SNV', 'WECC_UT', 'WECC_WY','PL_NV1','PL_AZ1']

inCAonly=False

oldgeopath= '../../Exe_prodCF_NG_5/outputs/GEOMETRY/geometry_high.tsv'
#'../SERA/SERA_NEW_OUTPUTS/BASECASE_CY_5_AB3C4D/outputs/GEOMETRY/geometry_high.tsv'
# folder='../SERA/SERA_NEW_OUTPUTS/BASECASE_CY_5_AB3C4D/'
newgeopath= '../../Exe_prodCF_NG_5/outputs/GEOMETRY/geometry_high.tsv'
#'../SERA/geometry_high_newLoc.tsv'

oldserageo=pd.read_csv(newgeopath, sep='\t')
oldserageo['Type']=oldserageo['Network ID'].str[0:3]
# print(oldserageo['Type'].value_counts())
keep=oldserageo[(oldserageo['Type']=="Cav") | (oldserageo['Type']=="WEC") | (oldserageo['Type']=="PL_")]
keep=keep.reset_index(drop=True)
if inCAonly:
    keep=keep[keep['Network ID'].isin(WECC_inCA)]
# display(keep)

serageo_new=keep.copy(deep=True).reset_index(drop=True)
for i in range(len(df)):
    # print(i)
    tazrow=df.loc[i,:]
    serageo_new.loc[len(serageo_new.index)] = ["TAZ_"+str(tazrow['Network ID']), 'center', tazrow["Lon"],tazrow["Lat"],'TAZ'] 

print(len(keep),len(serageo_new))
# serageo_new

KeyError: 'Network_ID'

In [ ]:
serageo_new[serageo_new['Network ID'].str.contains("PL_")]

In [ ]:
#####
# Create Delaunay triangles from caves, WECC centers and TAZs
#####

def order_ascend(a, b):
    return [a,b] if a < b else [b,a]

def dist(a,b):
    return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)

xs=list(serageo_new['X'])
ys=list(serageo_new['Y'])

points=[[xs[i],ys[i]] for i in range(0,len(xs))]
points=np.array(points)
tri = Delaunay(points)

# plt.figure(figsize=(20,15))
# plt.triplot(points[:,0], points[:,1], tri.simplices)
# # plt.plot(points[:,0], points[:,1], 'o')
# plt.show()


full_list_of_edges=[]
list_of_edges=[]
list_of_edges_indices=[]
for triangle in tri.simplices:
    # print(triangle)
    for p1,p2 in [[0,1],[1,2],[2,0]]:
        edge_indices=order_ascend(triangle[p1],triangle[p2])
        # print(edge_indices,end=" ")
        # print(points[edge_indices[0]],points[edge_indices[1]])
        full_list_of_edges.append([edge_indices,points[edge_indices[0]].tolist(),points[edge_indices[1]].tolist()])
        if edge_indices not in list_of_edges_indices:
            list_of_edges.append([edge_indices,points[edge_indices[0]].tolist(),points[edge_indices[1]].tolist()])
            list_of_edges_indices.append(edge_indices)
print("Number of unique edges",len(list_of_edges))

# algorithm="Gabriel"
# algorithm="Urquhart"
algorithm="Both"

pointslist=points.tolist()
reduced_list_of_edges=[]
removed_edges=[]
############Gabriel###############
if algorithm=="Gabriel" or algorithm=="Both":
    for edge in list_of_edges:
    # print(edge)
        p1=edge[1]
        p2=edge[2]
        center=[(p1[0]+p2[0])/2,(p1[1]+p2[1])/2]
        rad=dist(center,p1)-.0001 #rad is the radius of the circle between points 1 and 2 of an existing edge 
        # print(p1,p2,center,rad)
        #get list of points in bounding box of center of circle
        inside2=[point for point in pointslist if dist(point,center)<rad]
        #if there are points inside, don't add this edge to the save list
        if len(inside2)>0:
        #     reduced_list_of_edges.append(edge)
            removed_edges.append(edge)
    print(len(removed_edges)," removed after Gabriel")
############Urquhart###############
if algorithm=="Urquhart" or algorithm=="Both":
    threshold=.75 #degree
    removemax=False
    if algorithm=="Urquhart":
        removed_edges=[]
    for i in range(0,len(full_list_of_edges),3):
        side_lengths=[]
        for j in range(0,3):
            side_lengths.append(dist(full_list_of_edges[i+j][1],full_list_of_edges[i+j][2]))
        maxside=max(side_lengths)
        if maxside<threshold: ## only remove longest edges that are smaller than threshold
            maxind=side_lengths.index(maxside)
            removemax=True
        else:
            removemax=False
            maxind=4
        for j in range(0,3):
            if j==maxind and removemax==True:
                removed_edges.append(full_list_of_edges[i+j])
            # else:
            #     reduced_list_of_edges.append(full_list_of_edges[i+j])

removed_edges            
# removed_edge_list=list(map(lambda x: x[0],removed_edges))
removed_edge_list=[x[0] for x in removed_edges]
# removed_edge_list
added_edges=[]
for i in range(len(full_list_of_edges)):
    if full_list_of_edges[i][0] not in removed_edge_list and full_list_of_edges[i][0] not in added_edges:
        reduced_list_of_edges.append(full_list_of_edges[i])
        added_edges.append(full_list_of_edges[i][0])

    
print(len(list_of_edges),len(reduced_list_of_edges),len(reduced_list_of_edges)/len(list_of_edges))

# fig = plt.figure(figsize=(12,8))
# ax = plt.axes()
# for i in range(len(reduced_list_of_edges)):
#     edge=reduced_list_of_edges[i]
#     x=[edge[1][0],edge[2][0]]
#     y=[edge[1][1],edge[2][1]]
#     ax.plot(x,y,c='b')
    
maplinks = folium.Map(location=[origtazdem.Lat.mean(), df.Lon.mean()], 
                 # width=300,height=400,
                 tiles="cartodbpositron", zoom_start=5, control_scale=True)
maplinks

feature_group=folium.FeatureGroup('original')

for i in range(len(list_of_edges)):
    coord1=(list_of_edges[i][1][1],list_of_edges[i][1][0])
    coord2=(list_of_edges[i][2][1],list_of_edges[i][2][0])
    lineseg = [
        coord1, coord2
    ]
    folium.PolyLine(lineseg, weight=1,color="blue",tooltip="link_"+("0000"+str(i+1))[-4:]).add_to(feature_group)
feature_group.add_to(maplinks)

feature_group=folium.FeatureGroup('reduced')
for i in range(len(reduced_list_of_edges)):
    coord1=(reduced_list_of_edges[i][1][1],reduced_list_of_edges[i][1][0])
    coord2=(reduced_list_of_edges[i][2][1],reduced_list_of_edges[i][2][0])
    redlineseg = [
        coord1, coord2
    ]
    folium.PolyLine(redlineseg, weight=1,color="red",tooltip="link_"+("0000"+str(i+1))[-4:]).add_to(feature_group)
feature_group.add_to(maplinks)
folium.LayerControl().add_to(maplinks)

maplinks.save('Links_CAonly_'+str(targetTAZ)+'.html')
maplinks

In [ ]:
### Make new geometry file

lr=['left','right']
print(len(serageo_new))
serageo_new2=serageo_new.copy(deep=True)
k=len(serageo_new2.index)
print(k)
for i in range(len(reduced_list_of_edges)):
    edge=reduced_list_of_edges[i]
    linkname="link_"+("000"+str(i+1))[-4:]
    # print(linkname)
    coords=[edge[1],edge[2]]
    for j in range(len(lr)):
        side=lr[j]
        lon=coords[j][0]
        lat=coords[j][1]
        serageo_new2.loc[k] = [linkname, side, lon,lat,'link'] 
        # print(k)
        k+=1

print(len(serageo_new2))
serageo_new2=serageo_new2.drop(columns=['Type'])
serageo_new2.to_csv('new'+str(targetTAZ)+'_newLoc_geometry.tsv', sep = '\t',index=False)
#link_<num>    right/left.    Lon.   Lat.  link

In [ ]:
######
##  Updating Nodes file for SERA
######

nodes = pd.read_csv('nodes_newPlantsTAZ.tsv',sep='\t')
nodes = nodes[(nodes['Network ID'].str.contains("WEC")) | (nodes['Network ID'].str.contains("Cav")) | (nodes['Network ID'].str.contains("PL_"))]
if inCAonly:
    nodes= nodes[nodes['Network ID'].isin(WECC_inCA)]
nodes=nodes.reset_index(drop=True)
display(nodes)

# nodes.loc[len(nodes)-1,:]
# TAZ_6554	-116.926930	32.803945	0	No	0	0	0
print(len(nodes))
lennodes=len(nodes.index)
for i in range(len(tazdem2)):
    tazrow=tazdem2.loc[i]
    # display(tazrow)
    # print(len(nodes.index), end=" ")
    # print(['TAZ_'+str(tazrow['TAZ12']),tazrow['Lon'],tazrow['Lat'],0,'No',0,0,0])
    nodes.loc[lennodes+i]=['TAZ_'+str(tazrow['TAZ12']),tazrow['Lon'],tazrow['Lat'],0,'No',0,0,0]
    
nodes
print(len(nodes))
nodes.to_csv('nodes_new'+str(targetTAZ)+'_newLoc_TAZ.tsv', sep = '\t',index=False)

In [ ]:
######
##  Updating links file for SERA
######

oldlinksdf = pd.read_csv('links_386TAZ.tsv',sep='\t')
#Network ID	From Node ID	To Node ID	Length [km]	Cost [$]	Cost [$/yr]	Transmission?	Delivery?	Geometry [WKT]
#link_2	TAZ_5011	TAZ_3601	31	0	0	True	False	LINESTRING (-117.918 33.99953, -118.1084 34.23...
display(oldlinksdf[0:3])
linksdf=oldlinksdf[0:0].copy(deep=True)
for i in range(len(reduced_list_of_edges)):
    # print(edge)
    edge=reduced_list_of_edges[i]
    node1=serageo_new.loc[edge[0][0],:]
    node2=serageo_new.loc[edge[0][1],:]
    tmpdist=round(geopy.distance.geodesic([edge[1][1],edge[1][0]], [edge[2][1],edge[2][0]]).km)  #lat/lon
    geostring="LINESTRING ("+str(edge[1][0])+" "+str(edge[1][1])+", "+str(edge[2][0])+" "+str(edge[2][1])+")"
    linksdf.loc[i]=["link_"+("000"+str(i+1))[-4:],node1['Network ID'],node2['Network ID'],tmpdist,0,0,True,False,geostring]
linksdf.to_csv('links_newLoc_'+str(targetTAZ)+'TAZ.tsv', sep = '\t',index=False)
linksdf['Length [km]'].describe()

In [ ]:
######
## Zone files #inputs/network/zones_cavern-newstieve.tsv
##            #inputs/network/zones_ipm-newstieve.tsv  
######

cave_zonedf = pd.read_csv('zones_cavern-386TAZ.tsv',sep='\t')
cave_zonedf=cave_zonedf.sort_values(by="Network ID",ascending=True)
cave_zonedf=cave_zonedf[(cave_zonedf['Network ID'].str.contains("Cav")) | (cave_zonedf['Network ID'].str.contains("WEC"))]
if inCAonly:
    cave_zonedf=cave_zonedf[cave_zonedf['Network ID'].isin(WECC_inCA)]
cave_zonedf=cave_zonedf.reset_index(drop=True)
tazlist=list(tazdem4['Network ID'])
linklist=list(linksdf['Network ID'])
print(len(cave_zonedf),len(tazlist),len(linklist))
for taz in tazlist:
    cave_zonedf.loc[len(cave_zonedf)]=[taz,"No Salt Cavern Available",1]
for link in linklist:
    cave_zonedf.loc[len(cave_zonedf)]=[link,"No Salt Cavern Available",1]
cave_zonedf.to_csv('zones_cavern_newLoc-'+str(targetTAZ)+'TAZ.tsv', sep = '\t',index=False)
cave_zonedf

# zone_ipm code needs to be updated to place links and tazs into correct WECC zone
- Use geopandas or other geospatial library to place tazs into the regional polygons
- for the links, need to calculate fraction of link in potentially multiple regional polygons calculate polygon intersections with the lines.

- first check if both ends of link are in a single region if so, done
- otherwise add a number of nodes N to the link (e.g. 10) and get coordinates of these N nodes and determine what fraction of these N nodes lie in each region (N is based on the length of link)

In [ ]:

#######
# This one is TEMPORARY as we need code to place each taz or link into a specific Zone
#######
zonedf=pd.read_csv('zones_ipm-newLoc.tsv',sep='\t')
zonedf=zonedf[(zonedf['Network ID'].str.contains("Cav")) | (zonedf['Network ID'].str.contains("WEC")) | (zonedf['Network ID'].str.contains("PL_"))]
if inCAonly:
    zonedf=zonedf[zonedf['Network ID'].isin(WECC_inCA)]
zonedf=zonedf.reset_index(drop=True)
for taz in tazlist:
    zonedf.loc[len(zonedf)]=[taz,'Zone_WECC_SCE',1.0]
for link in linklist:
    zonedf.loc[len(zonedf)]=[link,'Zone_WECC_SCE',1.0]
zonedf.to_csv('zones_ipm_newLoc-'+str(targetTAZ)+'TAZ.tsv', sep = '\t',index=False)
display(zonedf)

#######
# This one is also TEMPORARY as we need code to place each taz or link into a specific Zone
#######
terrdf=pd.read_csv('territories-newLoc.tsv',sep='\t')
terrdf=terrdf[(terrdf['Network ID'].str.contains("Cav")) | (terrdf['Network ID'].str.contains("WEC")) | (terrdf['Network ID'].str.contains("PL_"))]
if inCAonly:
    terrdf=terrdf[terrdf['Network ID'].isin(WECC_inCA)]
terrdf=terrdf.reset_index(drop=True)
for taz in tazlist:
    terrdf.loc[len(terrdf)]=[taz,'WECC_SCE',1.0]
for link in linklist:
    terrdf.loc[len(terrdf)]=[link,'WECC_SCE',1.0]
terrdf.to_csv('territories_newLoc-'+str(targetTAZ)+'TAZ.tsv', sep = '\t',index=False)
terrdf

In [ ]:
# zonedf[zonedf['Network ID']=='PL_CA1']

In [ ]:
#####
# DONE
######

In [ ]:
def which_region_contains_point(regiondf,point):
    for i in range(len(regiondf)):
        print(regiondf.loc[i]['geometry'].contains(point))
        if regiondf.loc[i]['geometry'].contains(point):
            return (i,regiondf.loc[i]['IPM_Region'])
    return (None,"None")

def which_region_contains_coord(regiondf,lon,lat):
    point=geopandas.points_from_xy(x=[lon], y=[lat])[0]
    for i in range(len(regiondf)):
        # print(regiondf.loc[i]['geometry'].contains(point))
        if regiondf.loc[i]['geometry'].contains(point):
            return (i,regiondf.loc[i]['IPM_Region'])
    return (None,"None")
points=geopandas.points_from_xy(x=[-122.4], y=[38.2])
        
# regions.loc[15]['geometry'].contains(points[0])
# which_region_contains_point(regions,points[0])
which_region_contains_coord(regions,-122.4,38.2)

In [ ]:
same=0
diff=0

def create_coord_list(c1,c2,steps):
    stepsize=[(c2[0]-c1[0])/(steps-1),(c2[1]-c1[1])/(steps-1)]
    coordlist=[]
    for i in range(steps):
        coordlist.append([c1[0]+stepsize[0]*i,c1[1]+stepsize[1]*i])

    return coordlist

for ind in zonedf.index:
    row=zonedf.loc[ind]

    if "TAZ" in row['Network ID']:
        taz=row['Network ID']
        tazrow=nodes[nodes['Network ID']==taz]
        # print(taz)
        # display(tazrow)
        reg=which_region_contains_coord(regions,tazrow['X'],tazrow['Y'])
        # print(reg)
        zonedf.loc[ind,'Zone']="Zone_"+reg[1]
        zonedf.loc[ind,'Fraction']=1
    if "link" in row['Network ID']:
        link=row['Network ID']
        # linkrow=linksdf[linksdf['Network ID']==link]
        coord1=[linkrow.loc[0,'X'],linkrow.loc[0,'Y']]
        coord2=[linkrow.loc[1,'X'],linkrow.loc[1,'Y']]
        linkrow=serageo_new2[serageo_new2['Network ID']==link].reset_index(drop=True)
        regs=[which_region_contains_coord(regions,coord1[0],coord1[1])[1],which_region_contains_coord(regions,coord2[0],coord2[1])[1]]
        if regs[0]==regs[1]:
            print("same")
            same+=1
        else:
            print("different")
            linkregions=[]
            interior_coord=create_coord_list(coord1,coord2,10)
            for i in range(len(interior_coord)):
                linkregions.append(which_region_contains_coord(regions,interior_coord[i][0],interior_coord[i][1])[1])
            print(set(linkregions))
            diff+=1
print(same,diff)
        # print(link)
        # display(linkrow)
        # print(zonedf.loc[ind,'Zone'])
        # print(row)
zonedf

In [ ]:
maplinks = folium.Map(location=[origtazdem.Lat.mean(), df.Lon.mean()], 
                 # width=300,height=400,
                 tiles="cartodbpositron", zoom_start=4, control_scale=True)
maplinks

feature_group=folium.FeatureGroup('original')

for i in range(len(list_of_edges)):
    coord1=(list_of_edges[i][1][1],list_of_edges[i][1][0])
    coord2=(list_of_edges[i][2][1],list_of_edges[i][2][0])
    lineseg = [
        coord1, coord2
    ]
    folium.PolyLine(lineseg, weight=1,color="blue",tooltip="link_"+("0000"+str(i+1))[-4:]).add_to(feature_group)
feature_group.add_to(maplinks)

feature_group=folium.FeatureGroup('reduced')
for i in range(len(reduced_list_of_edges)):
    coord1=(reduced_list_of_edges[i][1][1],reduced_list_of_edges[i][1][0])
    coord2=(reduced_list_of_edges[i][2][1],reduced_list_of_edges[i][2][0])
    redlineseg = [
        coord1, coord2
    ]
    folium.PolyLine(redlineseg, weight=1,color="red",tooltip="link_"+("0000"+str(i+1))[-4:]).add_to(feature_group)
feature_group.add_to(maplinks)
folium.LayerControl().add_to(maplinks)
maplinks
# lat=list(origtazdem.Lat)
# lon=list(origtazdem.Lon)
# size=list(origtazdem.loc[:,2050])
# names=list(origtazdem.TAZ12)

# feature_group=folium.FeatureGroup('original')
# for i in range(len(origtazdem)):
   
#     folium.Circle(
#         radius=10*size[i]**.5,
#         location=[lat[i], lon[i]],
#         popup=str(names[i])+"-"+str(round(size[i])),
#         color="blue",
#         fill_color="blue",
#         fill_opacity=1,
#         fill=True,
#     ).add_to(feature_group)
    
# feature_group.add_to(map)


# lat2=list(tazdem2.Lat)
# lon2=list(tazdem2.Lon)
# size2=list(tazdem2.loc[:,2050])
# names2=list(tazdem2.Names)
# Ntaz=list(tazdem2.Ntaz)

# feature_group=folium.FeatureGroup('clustered')
# for i in range(len(tazdem2)):
#     if Ntaz[i]>1:
#         outcolor="darkred"
#     else: 
#         outcolor="red"
#     folium.Circle(
#         radius=10*size2[i]**.5,
#         location=[lat2[i], lon2[i]],
#         popup=str(Ntaz[i])+" taz\n"+str(round(size2[i]))+" kg/d\ntaz#\n"+str(names2[i]),
#         color=outcolor,
#         fill=True,
#         fill_opacity=1,
#     ).add_to(feature_group)
# feature_group.add_to(map)
# folium.LayerControl().add_to(map)